# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S-_MmDY5DMXx7WzMKP9Vp2FNs3djgWRf
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
# %matplotlib inline
import sklearn
from sklearn.utils import shuffle

LLM_generated_essay_PaLM = pd.read_csv("LLM_generated_essay_PaLM.csv")
train_essays = pd.read_csv("train_essays.csv")

df = pd.concat([LLM_generated_essay_PaLM, train_essays])

df.head()